### ISSUE TITLE
決済PFのテストアカウント取得

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#11]
## 概要
決済PFのテスト環境と接続するためのアカウント取得を行う。

## 詳細
Stripeのテストアカウント取得（詳細不明）
※アカウント取得せずにテストできるのであればタスク不要

## 成果物
アカウント情報

**Comment by TAKO-zhangyu** [comment]
取得完了しました。
メンバーの皆さんにメールアドレスを共有していただき、Stripeのダッシュボードに登録をします。
登録したメンバーは、Stripeのダッシュボードに入ることができます。

補足：
- ひろみちさんは「オーナー」として登録
- その他の開発メンバーの方は「開発者」として登録
