### ISSUE TITLE
[機能開発]ポートフォリオ の編集機能

### ISSUE THREAD

**Issue by fumi238000** [great084/creator_match_pf#125]
## 概要

- ポートフォリオ機能の実装
## 実装内容

- テーブル・コントローラ・viewの作成の作成
- アクションの実装
- youtubeの埋め込み機能

## 成果物

- コード
- 写真
## その他情報

- Viewファイルの作成を行った場合は、フロント開発に受け渡すため、以下のファイルの該当画面の「Viewファイル受け渡し」欄を更新すること
[URL・画面一覧](https://docs.google.com/spreadsheets/d/1bzDHyIJzBkSP1a7gJ7gRDCZuEN15RQEg81J4zbuFqKA/edit#gid=0)

**Comment by fumi238000** [comment]
## メモ
- テーブルで、ポートフォリオ のURLのidを格納するカラムがあるが、どのように使用するのか確認すること

**Comment by fumi238000** [comment]
## MEMO
- URLのバリデージョン 参考資料 [RailsでURLのバリデーション
](https://blog.bitarts.jp/entry/2015/09/14/rails_url_validate.html)

**Comment by great084** [comment]
質問回答します。
>1.テーブルで、portfolio_url_idを格納するカラムがあるが、どのように使用するのでしょうか？

Youtube動画埋め込み時にデータベースとコントローラ内での処理が必要になります。
必要なカラムはurlを格納できるstring型のurlカラムと、urlの末11文字を格納するstring型のurl_idカラムです。

＞2.カラム名が長いため、省略しても良いでしょうか？（ex.portfolio_title　→ title)
そうですね。接頭詞portfolioは不要です。

>3データ型がtextだとindexを貼れないのですが、portfolio_textにindexを貼る必要はありますか？
不要です。検索・ソートに使うとは思えないので

>4ER図を見ると1対多ですが、一人のクライアントが複数のポートフォリオを登録できる想定でよろしいでしょうか？
はい、その認識であっています。

>5ポートフォリオのTOPには、画像が入る設計ですが、URLを元に動画が入るイメージでよろしいでしょうか？
はい、URLとURL_IDを元にyoutubeの動画が入る予定です。

**Comment by OhtakeYusuke** [comment]
既に回答してくださっていますが自分が関係している部分の回答をします。
1.テーブルで、portfolio_url_idを格納するカラムがあるが、どのように使用するのでしょうか？
これはYoutubeの動画を利用する際に必要なので記載しました。既にSlackでもひろみちさんが書いてくださっていますが、教材にあるのでそちらを参考にくださると助かります！

5ポートフォリオのTOPには、画像が入る設計ですが、URLを元に動画が入るイメージでよろしいでしょうか？
これは動画になります。縦長動画もありますが、縦:横＝9:16の枠内に強制的に入れる予定です。
