### ISSUE TITLE
【マッチング】クリエイター検索

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#16]

**Comment by fumi238000** [comment]
## 概要
- クリエイターを検索できること

## 詳細
- ransackの導入
- フォームの作成
- 検索した結果、条件に一致したカードを表示させる

## 検討
- タグは、フリーワード検索の対象としなくでもよいか
- 検索対象の決定は、Meneの名前のみ？それ以外も含めるか？
-  検索対象が０の場合の画面表示方法は？

**Comment by fumi238000** [comment]
## 行動
- [ ] ransackの導入
- []

## 参考資料
- [Github](https://github.com/activerecord-hackery/ransack)
- [検索機能](https://www.yanbaru-code.com/texts/221)
