### ISSUE TITLE
【マッチング】仕事の各種アクション

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#24]
- 条件の合意
- 納品連絡
- 納品物の確認完了連絡

**Comment by fumi238000** [comment]
# MEMO
## 概要
- 仕事の各種アクションの作成

## 詳細
①条件の合意
- 条件を合意させるためのアクション？
- 「条件に合意する」ボタンの作成
②納品連絡
- クリエイターが納品物のURLをチャットに送付後、クライアントに通知が届く設定
- メールか、アプリ上で通知を表示させるか 
- 「納品完了」ボタンを表示させる
③納品物の確認完了連絡
- クリエイターが納品物を確認した旨を伝える、「完了」ボタンを作成する

## 検討
- 詳細を明確にする必要がある。

**Comment by fumi238000** [comment]
# 行動
### テーブルの作成
  - [ ] Task
  - [ ] Message
  - [ ] Review
### コントローラの作成
  - [ ] Task
  - [ ] Message
  - [ ] Review
### viewの作成
  - [ ] Task(show,edit)
  - [ ] Review(new)

**Comment by fumi238000** [comment]
## 行動
- [ ] enumを変数にする
- [ ] enum-helperで日本語化
- [ ] enum関連の表示を変更
- [ ] change_statsuメソッドを実装
  - 条件分岐が複数存在したため、ステータス判定メソッド`statsus?`を実装
  - ステータスによって、表示を変更
- [ ] お知らせ通知を実装
