### ISSUE TITLE
【決済】テーブル設計（売上金、口座情報）

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#35]
## 概要
DB設計の成果物としてTBL設計を行う。

対象：TBL
- 売上金、口座情報

## 詳細
ER-図（必要に応じてユースケース、ワイヤーフレーム）をインプットに
TBL毎に、キー項目、項目名称、型、インデックス、default値などを具体化する。

## その他
ER−図の修正が必要であれば全体連絡ください。
担当タスク外のTBL作成に要望（追加項目など）あれば、該当するタスクのイシューにコメントしてください。

## 成果物
TBL設計

**Comment by TAKO-zhangyu** [comment]
- 振込のステータスなどをどう管理するのか
- クライアントの支払いの履歴（日時、結果）をTBLに記録しておくかどうか
  - 画面には出さないが、調査などができるように残したほうがベター

**Comment by TAKO-zhangyu** [comment]
クライアントの支払いの履歴は記録しない方向で考えています。

理由:
- Createrのテーブルにあるcustomer_idから取得できる

**Comment by TAKO-zhangyu** [comment]
- 振込のステータスなどをどう管理するのか

ステータスの種類:
- applied - 申請済（ユーザーの申請が完了したのみで、まだ受理されていない）
- application_accepted - 申請受理（管理者が申請を確認, 受理。振込準備に入る）
- application_denied - 申請却下（管理者が申請を拒否したい際に却下する）
- payout_success - 振込完了（管理者がユーザーに振込完了を伝える）
- payout_failed - 振込失敗（管理者がユーザーに振込失敗を伝える）

ステータス管理の処理について
- システムの仕様上、applied以外は管理者が手動でステータスを更新する必要がある。
- 管理画面にそれぞれのボタンを追加するなどをして、ステータスを更新する想定。
- ボタンを押すたびにステータスが更新される処理を実装する。
- 誤って異なるボタンが押されることを想定し、確認のフラッシュメッセージの実装は必須。
- ステータスを戻すボタンを実装する必要もありか。

**Comment by TAKO-zhangyu** [comment]
ステータスの種類に「申請失敗」は必要でしょうか？

**Comment by great084** [comment]
@TAKO-zhangyu 
> クライアントの支払いの履歴は記録しない方向で考えています。
> 理由:
> Createrのテーブルにあるcustomer_idから取得できるから

管理者は、管理画面はcustomer_idを取得して、それをもとにStripeの画面から検索すれば履歴が確認できるということでしょうか？
であれば、支払履歴は記録しない方向で良いと思います。
気になるのは、決済に失敗した場合ですが、エラーになったらクライアントがリアルタイムで画面上で確認できますよね？

> 振込のステータスなどをどう管理するのか
> ステータスの種類:
「申請却下」の実際のイメージが沸かないのですが、どのような場合に却下するのでしょうか？
ステータスは簡潔に「振込申請中（上記の申請済）」と「振込完了」のみで良いと思いました。
振込失敗した場合などは管理者が直接メール連絡するなどマニュアルで操作してもらえばいいのかなと。

> ステータス管理の処理について

> システムの仕様上、applied以外は管理者が手動でステータスを更新する必要がある。
認識あっています。

> 管理画面にそれぞれのボタンを追加するなどをして、ステータスを更新する想定。
> ボタンを押すたびにステータスが更新される処理を実装する。
ボタンでも、プルダウン選択でもよいので、ActiveAdminの機能で実装できるステータス更新の方法で良いと思います。

> 誤って異なるボタンが押されることを想定し、確認のフラッシュメッセージの実装は必須。
たしかにそうですね。実装しましょう。

> ステータスを戻すボタンを実装する必要もありか。
今はいらないと思います。

あとは、ステータス変更した後の通知として、以下が必要だと思います。
振込申請をした場合は、管理者に対してメール連絡
振込完了にステータス変更した場合は、クリエイターに対してメール連絡

**Comment by TAKO-zhangyu** [comment]
@great084 
### クライアントの支払いの履歴は記録について
> 管理者は、管理画面はcustomer_idを取得して、それをもとにStripeの画面から検索すれば履歴が確認できるということでしょうか？

Stripeのダッシュボードからもみれますし、システム上で取得することもできます。
支払履歴は記録しない方向で進めますね。

> 気になるのは、決済に失敗した場合ですが、エラーになったらクライアントがリアルタイムで画面上で確認できますよね？

決済に失敗した場合、決済処理は行われずに決済画面に再遷移します。エラーコードも即座に出るはずです。
Stripe Checkoutの仕様では、決済が完了するまで画面の遷移を行いません。

ただ、実際に検証するには、Stripe Checkoutを本番モードで使ってみないと分からないです。
テストモードではテストカード以外は受け付けない設定になっており、テストカード以外のカードで決済しようとすると即座にエラーがでます。

決済処理が行われないので、ダッシュボードにログは残リませんでした。

**Comment by TAKO-zhangyu** [comment]
@great084 

### ステータス管理の処理について

> 「申請却下」の実際のイメージが沸かないのですが、どのような場合に却下するのでしょうか？
今回は売上金額をシステム上で管理するので、仮に間違いがあった場合は却下できるように、、、という選択を設けた方が良いのかなという判断でした。

> ステータスは簡潔に「振込申請中（上記の申請済）」と「振込完了」のみで良いと思いました。
> 振込失敗した場合などは管理者が直接メール連絡するなどマニュアルで操作してもらえばいいのかなと。
例えば振込失敗した場合、ステータスはnilとなるのでしょうか？それとも、申請中のままでしょうか？

### ステータス管理の処理について

> ステータス変更した後の通知として、以下が必要だと思います。
> - 振込申請をした場合は、管理者に対してメール連絡
> - 振込完了にステータス変更した場合は、クリエイターに対してメール連絡
承知しました。こちら実装いたします。

**Comment by great084** [comment]
**クライアントの支払い履歴の記録について**
> 
> Stripeのダッシュボードからもみれますし、システム上で取得することもできます。
> 支払履歴は記録しない方向で進めますね。

了解しました。

> 決済に失敗した場合、決済処理は行われずに決済画面に再遷移します。エラーコードも即座に出るはずです。
> Stripe Checkoutの仕様では、決済が完了するまで画面の遷移を行いません。（オーソリ・キャプチャーを使う場合を除く）
> 
> ただ、実際に検証するには、Stripe Checkoutを本番モードで使ってみないと分からないです。
> テストモードではテストカード以外は受け付けない設定になっており、テストカード以外のカードで決済しようとすると即座にエラーがでます。

なるほど、テストモードだと検証ができないんですね。（有効期限を過去日にしてもだめでした？）
ま、決済画面に最遷移する仕様を信じて、本番環境構築後に試してエラーが把握できるか確認してみて、だめならまた考えましょう。

**Comment by great084** [comment]
**ステータス管理の処理について**

>今回は売上金額をシステム上で管理するので、仮に間違いがあった場合は却下できるように、、、という選択を設けた方が良いのかなという判断でした。

了解です。確かに（あってはいけないですが）ありえない話ではないですね。
ちょっとここはユーザと確認しましょう。

実装するとしたら売上金合計額の増減は以下のような感じですかね。
「振込申請中」：  クリエイターの売上金合計額から振込申請額を減額
「申請却下」or「振込失敗」： クリエイターの売上金合計額に振込申請額を戻す？ or そのままにしておいてマニュアルで頑張る（メール連絡するとか）
「振込完了」： 売上金合計額は特に変動なし。ステータス変更のみ

**Comment by TAKO-zhangyu** [comment]
@great084 
> 有効期限を過去日にしてもだめでした？

こういったような入力時点で無効と明らかなものは赤字の警告が出るので大丈夫です！この状態では決済ボタンを押すことはできないです。

### ステータス管理の処理について

> 実装するとしたら売上金合計額の増減は以下のような感じですかね。
> 「振込申請中」： クリエイターの売上金合計額から振込申請額を減額
> 「申請却下」or「振込失敗」： クリエイターの売上金合計額に振込申請額を戻す？ or そのままにしておいてマニュアルで頑張る（メール連絡するとか）
> 「振込完了」： 売上金合計額は特に変動なし。ステータス変更のみ

同じ認識です。
ただ、振込失敗のところで新たに疑問が湧いてきたので、ステータス管理については一旦フローチャートにまとめた方が良さそうですね。

申請却下を実装するとした場合
- クリエイターの売上金合計額に振込申請額を戻す

振込失敗
- そのままにしておいてマニュアルで頑張る（メール連絡するとか）
- 仮に「手は尽くした、どうしても無理だ、、」となった場合、申請却下の扱いとなる？

**Comment by TAKO-zhangyu** [comment]
[振込申請フローチャート](https://drive.google.com/file/d/1i98l60KUNi4n3tnn6fsHnXOZ8li7KCEm/view?usp=sharing)
