### ISSUE TITLE
【会員】モデル, テーブルl作成(User, MemberInformation)

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#36]
## 概要

User(Client Creator)のモデル作成とTBL作成

## 実装内容

- User, Client, Creatorモデルの作成
- MemberInformationモデルの作成 （Userとの関連付け）
- STIによる継承の定義
- TBLの作成

※ 認証機能にdeviseを利用するならば、deviseのインストールでモデル、TBLを作成して、その後カスタマイズしたほうが楽かもしれません
※ 他テーブル(Menu, Taskなど）のアソシエーション定義は従属側のTBLのタスクで登録する

## 成果物

プログラムソース

**Comment by TAKO-zhangyu** [comment]
Clientの会員情報テーブルにcustomer_idカラムの追加をお願いいたします。
- 決済時にStripeから発行されるcustomer_idを格納するカラム
- customer_idから顧客の決済情報を取得することができる

**Comment by great084** [comment]
stripeのカスタマーidであることが分かるように
`stripe_customer_id`の方が良いですね。

**Comment by akihiro66** [comment]
`stripe_customer_id` はUsersテーブルではなく、MemberInformationsテーブルに追加すれば良いでしょうか？

**Comment by TAKO-zhangyu** [comment]
@akihiro66 
すみません、メッセージに今気づきました💦

> `stripe_customer_id` はUsersテーブルではなく、MemberInformationsテーブルに追加すれば良いでしょうか？

おそらくUsersテーブルになると思います。
`stripe_customer_id`に格納するcustomer_idは決済履歴などを確認するためのIDなので、名前や住所などを保存するMemberInformationsテーブルより適していると思います！
