### ISSUE TITLE
【マッチング】モデル, テーブルl作成(Menu)

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#38]
## 概要

Menuモデル作成とTBL作成

## 実装内容

- Menモデルの作成( Creatorモデルとの関連付け）
- TBLの作成(Userテーブルとの関連付け）
- テストデータの作成(db.seed)

## 成果物

プログラムソース

**Comment by fumi238000** [comment]
## 行動
- [ ] Menモデルの作成( Creatorモデルとの関連付け）
- [ ] TBLの作成(Userテーブルとの関連付け）
- [ ] テストデータの作成(db.seed)
