### ISSUE TITLE
ワイヤーの変更（メールアドレス変更、パスワード変更画面の追加）

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#44]
## 概要

メールアドレス変更、パスワード変更画面をワイヤーに追加する

### マイページ
-「メールアドレス変更」「パスワード変更」のリンクを設定（クライアント、クリエイターとも）

###  メールアドレス変更画面
現在のメールアドレスを表示し、変更後のメールアドレスを入力させ、送信

### パスワード変更画面
現在のパスワードと、変更後のパスワード、変更後のパスワード（変更後）を入力させ、送信

## 成果物

- サイトマップ
- ワイヤーフレーム

## その他情報

2/28までに対応をお願いします。

**Comment by OhtakeYusuke** [comment]
## 成果物
パスワード変更画面
メールアドレス変更画面
それぞれ作成完了

```
備考

サイトマップページの内容がフッターと全く同じになります。全部被っているのでサイトマップ作成するならば被っても良いか確認したいです。
```

**Comment by great084** [comment]
>パスワード変更画面
>メールアドレス変更画面

画面レイアウトOKです。

- ワイヤーのファイル名称が「ログイン – 2,3」となっているので修正してもらえると助かります。

- 以下のマイページからのリンク設定も追加願います。
>「メールアドレス変更」「パスワード変更」のリンクを設定（クライアント、クリエイターとも）

- 以下のサイトマップですが、画面のサイトマップではなく、資料としての[サイトマップ](https://drive.google.com/file/d/1i1bBaLJE2RdGMRrCCyQw2LHR0-CRmjAN/view)になります。(私の方で修正しておきました）
画面のフッターには、おっしゃるとおりでサイトマップ不要だと思います。
>サイトマップページの内容がフッターと全く同じになります。全部被っているのでサイトマップ作成するならば被っても良いか確認したいです。

**Comment by OhtakeYusuke** [comment]
##　修正内容
>ワイヤーのファイル名称が「ログイン – 2,3」となっているので修正してもらえると助かります。
完了
```
備考
フミヤさんから「ページ名横にURL名をつけて欲しい」という要望もあったため追加修正
```

>以下のマイページからのリンク設定も追加願います。
>「メールアドレス変更」「パスワード変更」のリンクを設定（クライアント、クリエイターとも）
完了

>画面のフッターには、おっしゃるとおりでサイトマップ不要だと思います。
承知いたしました。

**Comment by great084** [comment]
確認しました。
OKです！
