### ISSUE TITLE
開発補助ツールを導入

### ISSUE THREAD

**Issue by great084** [great084/creator_match_pf#7]
## 概要
開発環境（Railsプロジェクト）に開発に必要な補助ツールを導入する。

※開発環境作成タスク実施後におこなうこと

## 詳細
開発環境（Railsプロジェクト）に開発に必要な補助ツールを選定して導入する。<br>
（機能開発ためのツールは各機能開発タスクで実施するため、このタスクでは不要）

- デバッガー(pry-debug?)
- コードチェッカー（rubocop?)

※他にこれまでの経験で必要なものがあれば選定して導入する

## 成果物
コード

**Comment by fumi238000** [comment]
# 行動
- [ ] デバッガーの導入
```
  gem 'pry-byebug'
```
- [ ] rubocopの導入

**Comment by great084** [comment]
@fumi238000 
検討ありがとうございます。

rubocopについては、初期設定は絶対に行ったほうが良いです。
（でないと、何でもかんでもチェックされて開発の効率が逆に著しく悪くなります）
rubocopの設定ファイルは世の中に出回っているので、探してみてください。
あと、railsのチェックも行ってくれるrubocop-railsも入れるといいかと。

自動実行についてもできるのであれば是非！私のようなズボラな人間はよく忘れます。

あと、rubocopに関して過去に記事を書いたので、ご参考までに。
https://qiita.com/great084/items/26803a5ae5a407018561

**Comment by fumi238000** [comment]
@great084 
ご返答ありがとうございます！

rubocopの初期設定終了後、プルリクを出したいと思います！
記事も参考にさせていただきます！

**Comment by fumi238000** [comment]
# 追記
- Rspecの導入
